praktyki/Models/Event.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace praktyki.Models
{
    [Table("event")]
    public partial class Event
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column("event_id")]
        [Display(Name = "Zdarzenie")]
        public int EventId { get; set; }
        [Required]
        [Column("description")]
        [Display(Name = "Opis")]
        public string Description { get; set;}
        [Required]
        [Column("description_long")]
        [Display(Name = "Szczegółowy opis")]
        public string DescriptionLong { get; set; }
        [Column("date")]
        [Display(Name = "Data")]
        public DateTime Date { get; set; }
        [Column("status")]
        [Range(0,3)]
        public int Status { get; set; }
        [Required]
        public int PointId { get; set; }
        [Display(Name = "Punkt")]
        public virtual Point Point { get; set; }
        public ICollection<EmployeeEvent> EmployeeEvents { get; set; }
    }
}

praktyki/Models/EventViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace praktyki.Models
{
    public class EventViewModel
    {
        [Display(Name = "Opis")]
        public string Description { get; set; }
        [Display(Name = "Data")]
        public DateTime Date { get; set; }
        public Client Client { get; set; }
        [Display(Name ="Szczegółowy opis")]
        public string DescriptionLong { get; set; }
        public int PointId { get; set; }
        public ICollection<int> EmployeesId { get; set; }
        public int Status { get; set; }
    }
}

praktyki/Controllers/EventController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using praktyki.Data;
using praktyki.Models;

namespace praktyki.Controllers
{
    public class EventController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EventController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Map(string FromDate, string ToDate, int? Status)
        {
            DateTime dt1 = new DateTime();
            DateTime dt2 = new DateTime();
            ViewBag.Status = null;
            try
            {
                dt1 = DateTime.Parse(FromDate);
                dt2 = DateTime.Parse(ToDate);
                ViewData["DateTime1"] = FromDate;
                ViewData["DateTime2"] = ToDate;
            }
            catch (ArgumentNullException)
            {
                dt1 = DateTime.Now.AddDays(-30);
                dt2 = DateTime.Now;
                ViewData["DateTime1"] = XmlConvert.ToString(dt1, (XmlDateTimeSerializationMode)3).Remove(XmlConvert.ToString(dt1, (XmlDateTimeSerializationMode)3).IndexOf("."));
                ViewData["DateTime2"] = XmlConvert.ToString(dt2, (XmlDateTimeSerializationMode)3).Remove(XmlConvert.ToString(dt2, (XmlDateTimeSerializationMode)3).IndexOf("."));

            }
            var applicationDbContext = _context.Event.Include(p => p.Point).ThenInclude(c => c.Client).Where(d => d.Date >= dt1 && d.Date <= dt2);
            if (Status >= 0 && Status < 4)
            {
                applicationDbContext = (IOrderedQueryable<Event>)applicationDbContext.Where(s => s.Status == Status);
                ViewBag.Status = Status;
            }
            return View(await applicationDbContext.ToListAsync());
        }
        // GET: Event
        public async Task<IActionResult> Index()
        {
            return View(await _context.Event.ToListAsync());
        }

        // GET: Event/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // GET: Event/Create
        public IActionResult Create(int? clientId, int? pointId)
        {
            if (clientId.HasValue && pointId.HasValue)
            {
                ViewBag.Employees = new MultiSelectList(_context.Employee, "EmployeeId", "FullName");
                ViewBag.Points = new SelectList(_context.Point, "PointId", "Name", _context.Point.Find(pointId).PointId);
                ViewBag.Clients = new SelectList(_context.Client, "ClientId", "Name", _context.Client.Find(clientId).ClientId);
                ViewData["PassedId"] = true;
                ViewBag.PointId = pointId;
            }
            else
            {
                ViewBag.Employees = new MultiSelectList(_context.Employee, "EmployeeId", "FullName");
                ViewBag.Points = new SelectList(_context.Point, "PointId", "Name");
                ViewBag.Clients = new SelectList(_context.Client, "ClientId", "Name");
                ViewData["PassedId"] = false;
                ViewBag.PointId = 1;
            }

            return View();
        }

        // POST: Event/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventViewModel eventViewModel)
        {
            if (ModelState.IsValid)
            {
                Event @event = new Event()
                {
                    Description = eventViewModel.Description,
                    Date = eventViewModel.Date,
                    Point = _context.Point.Find(eventViewModel.PointId),
                    Status = eventViewModel.Status,
                    DescriptionLong = eventViewModel.DescriptionLong
                };
                _context.Add(@event);
                await _context.SaveChangesAsync();
                if (eventViewModel.EmployeesId != null)
                {
                    foreach (var item in eventViewModel.EmployeesId)
                    {
                        EmployeeEvent employeeEvent = new EmployeeEvent()
                        {
                            EployeeId = item,
                            EventId = @event.EventId
                        };
                        _context.Add(employeeEvent);
                        await _context.SaveChangesAsync();
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(eventViewModel);
        }

        // GET: Event/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event.FindAsync(id);
            if (@event == null)
            {
                return NotFound();
            }
            return View(@event);
        }

        // POST: Event/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("EventId,Description,DescriptionLong,Date,PointId,Status")] Event @event)
        {
            if (id != @event.EventId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    Event event2 = _context.Event.Find(id);
                    event2.Status = @event.Status;
                    event2.Date = @event.Date;
                    event2.Description = @event.Description;
                    event2.DescriptionLong = @event.DescriptionLong;
                    _context.Update(event2);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EventExists(@event.EventId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@event);
        }

        // GET: Event/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var @event = await _context.Event
                .FirstOrDefaultAsync(m => m.EventId == id);
            if (@event == null)
            {
                return NotFound();
            }

            return View(@event);
        }

        // POST: Event/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var @event = await _context.Event.FindAsync(id);
            _context.Event.Remove(@event);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EventExists(int id)
        {
            return _context.Event.Any(e => e.EventId == id);
        }
    }
}

praktyki/Views/Event/Create.cshtml
@model praktyki.Models.EventViewModel

@{
        ViewData["Title"] = "Dodaj zdarzenie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    bool blockSelect = (bool)ViewData["PassedId"];
    Dictionary<int, string> status = new Dictionary<int, string>();
    status.Add(0, "Zaplanowany");
    status.Add(1, "W trakcie");
    status.Add(2, "Zakończony");
    status.Add(3, "Coś poszło nie tak");
    SelectList sl = new SelectList(status.ToList(), "Key", "Value");
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionLong" class="control-label"></label>
                <textarea asp-for="DescriptionLong" rows="4" class="form-control"></textarea>
                <span asp-validation-for="DescriptionLong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="sl"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group" id="clientDiv">
                <label class="control-label">Klient</label>
                <select required="required" class="form-control" id="client" asp-items="ViewBag.Clients" onchange="changePoints(this)">
                    @if (blockSelect == false)
                    {
                        <option disabled selected>Wybierz klienta</option>
                    }
                </select>
            </div>
            <div class="form-group" id="pointDiv">
                <label asp-for="PointId" class="control-label">Punkt</label>
                <select class="form-control" asp-for="PointId" id="point" onchange="changeEmployees()"></select>
            </div>
            <div class="form-group" id="employeeDiv">
                <div class="d-flex mb-2">
                    <label class="control-label w-100">Osoby</label><a class="btn btn-primary d-flex align-items-center" style="color: #fff; cursor:pointer" onclick="changeEmployees()"><span class="fas fa-sync-alt mr-2"></span>Odśwież</a>
                </div>
                <select asp-for="EmployeesId" multiple class="form-control" id="employee"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>
<script>
    if ("@blockSelect" == "True") {
        console.log("czy if jest prawda? TAK!")
        document.getElementById("client").disabled = true;
        document.getElementById("point").disabled = true;
        document.getElementById("pointDiv").style.display = "block";
        document.getElementById("employeeDiv").style.display = "block";
        let selectList = document.getElementById("point");
        let option = document.createElement("option");
        fetch('https://localhost:44319/api/points')
            .then(response => response.json())
            .then(data => {
                data.map(point => {
                    if (point.pointId == @ViewBag.PointId) {
                        option.value = point.pointId;
                        option.textContent = point.name;
                        option.selected = true;
                        selectList.appendChild(option)
                    }
                });
            });

        let employeesId = [];
        let selectedId = document.getElementById("point").value;
        let selectList2 = document.getElementById("employee");
        fetch('https://localhost:44319/api/employeepoints')
            .then(response => response.json())
            .then(data => {
                console.log("przed mapowaniem wynikow z employeepoints")
                data.map(employeePoint => {
                    if (employeePoint.pointId == option.value) {
                        employeesId.push(employeePoint.employeeId);
                        console.log("dodano do listy emplyeesid: " + option.value);
                    }
                })
            });
        console.log(employeesId)
        fetch('https://localhost:44319/api/employees')
            .then(response => response.json())
            .then(data => {
                data.map(employee => {
                    if (employeesId.includes(employee.employeeId)) {
                        let option = document.createElement("option");
                        option.value = employee.employeeId;
                        option.textContent = employee.fullName
                        selectList2.appendChild(option);
                    }
                })
            });
        //(async function () {
        //    await changeEmployees();
        //})();
        console.log(document.getElementById("point").value);
    }
    else {
        document.getElementById("client").disabled = false;
        document.getElementById("point").disabled = false;
        document.getElementById("pointDiv").style.display = "none";
        document.getElementById("employeeDiv").style.display = "none";
        function changePoints() {
            $("#point").empty();
            let selectedClient = document.getElementById("client").value;
            let selectList = document.getElementById("point");
            let tmp = document.createElement("option");
            tmp.value = 0;
            tmp.textContent = "Wybierz punkt";
            tmp.selected = true;
            tmp.disabled = true;
            selectList.appendChild(tmp);
            fetch('https://localhost:44319/api/points')
                .then(response => response.json())
                .then(data => {
                    data.map(point => {
                        if (point.clientId == selectedClient) {
                            let option = document.createElement("option");
                            option.value = point.pointId;
                            option.textContent = point.name;
                            selectList.appendChild(option)
                        }
                    });
                });

            document.getElementById("pointDiv").style.display = "block";
        }
    }
    async function setPoints() {
        let selectList = document.getElementById("point");
        await fetch('https://localhost:44319/api/points')
            .then(response => response.json())
            .then(data => {
                data.map(point => {
                    if (point.pointId == @ViewBag.PointId) {
                        let option = document.createElement("option");
                        option.value = point.pointId;
                        option.textContent = point.name;
                        option.selected = true;
                        selectList.appendChild(option)
                    }
                });
            });
    }

    async function changeEmployees() {
        $("#employee").empty();
        let employeesId = [];
        console.log(document.getElementById("point").value);
        let selectedId = document.getElementById("point").value;
        console.log(document.getElementById("point").value);
        console.log("selectedId: " + selectedId)
        let selectList = document.getElementById("employee");
        await fetch('https://localhost:44319/api/employeepoints')
            .then(response => response.json())
            .then(data => {
                data.map(employeePoint => {
                    console.log("employeePoint.pointId: " + employeePoint.pointId + "---selectedId: " + selectedId);
                    if (employeePoint.pointId == selectedId) {
                        employeesId.push(employeePoint.employeeId);
                    }
                })
                console.log("skonczyło się mapowanie");
                console.log(document.getElementById("point").value);
            });
        await fetch('https://localhost:44319/api/employees')
            .then(response => response.json())
            .then(data => {
                data.map(employee => {
                    if (employeesId.includes(employee.employeeId)) {
                        let option = document.createElement("option");
                        option.value = employee.employeeId;
                        option.textContent = employee.fullName
                        selectList.appendChild(option);
                    }
                })
            });
        document.getElementById("employeeDiv").style.display = "block";
    }
    @*@foreach (var item in ViewBag.Points) {
        if (item.ClientId ==
            @:selectedClient
            ) {
        @:console.log(@item.ClientId);
        }
    }*@
</script>

praktyki/Views/Event/Delete.cshtml
@model praktyki.Models.Event

@{
    ViewData["Title"] = "Czy na pewno usunąć ten element?";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<h3>Czy na pewno usunąć ten element?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionLong)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DescriptionLong)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="EventId" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót do listy</a>
    </form>
</div>

praktyki/Views/Event/Details.cshtml
@model praktyki.Models.Event

@{
    ViewData["Title"] = "Szczegóły zdarzenia";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, string> status = new Dictionary<int, string>();
    status.Add(0, "Zaplanowany");
    status.Add(1, "W trakcie");
    status.Add(2, "Zakończony");
    status.Add(3, "Coś poszło nie tak");
    SelectList sl = new SelectList(status.ToList(), "Key", "Value", Model.Status);
}

<h1>Szczegóły zdarzenia</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DescriptionLong)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DescriptionLong)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-3">
            <select disabled asp-for="Status" class="form-control" asp-items="sl"></select>
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.EventId">Edytuj</a> |
    <a asp-action="Index">Powrót do listy</a>
</div>

praktyki/Views/Event/Edit.cshtml
@model praktyki.Models.Event

@{
    ViewData["Title"] = "Edytuj zdarzenie";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, string> status = new Dictionary<int, string>();
    status.Add(0, "Zaplanowany");
    status.Add(1, "W trakcie");
    status.Add(2, "Zakończony");
    status.Add(3, "Coś poszło nie tak");
    SelectList sl = new SelectList(status.ToList(), "Key", "Value", Model.Status);
}

<h1>@ViewData["Title"]</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="EventId" />
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DescriptionLong" class="control-label"></label>
                <textarea asp-for="DescriptionLong" rows="4" class="form-control"></textarea>
                <span asp-validation-for="DescriptionLong" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control" asp-items="sl"></select>
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>

praktyki/Views/Event/Index.cshtml
@model IEnumerable<praktyki.Models.Event>

@{
    ViewData["Title"] = "Lista zdarzeń";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>@ViewData["Title"]</h1>

<p>
    <a asp-action="Create">Dodaj nowe zdarzenie</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.EventId">Edytuj</a> |
                <a asp-action="Details" asp-route-id="@item.EventId">Szczegóły</a> |
                <a asp-action="Delete" asp-route-id="@item.EventId">Usuń</a>
            </td>
        </tr>
}
    </tbody>
</table>

praktyki/Views/Event/Map.cshtml
@model IEnumerable<praktyki.Models.Event>

@{
    ViewData["Title"] = "Mapa punktów";
    Layout = "~/Views/Shared/_Layout.cshtml";
    Dictionary<int, string> status = new Dictionary<int, string>();
    status.Add(0, "Zaplanowany");
    status.Add(1, "W trakcie");
    status.Add(2, "Zakończony");
    status.Add(3, "Coś poszło nie tak");
    SelectList sl = new SelectList(status.ToList(), "Key", "Value", ViewBag.Status);
}

<h1>@ViewData["Title"]</h1>
<style>
    .blankRow {
        height: 30rem !important;
    }
</style>
<p>
    <a asp-action="Create">Dodaj nowe zdarzenie</a>
</p>
<form id="advancedSearch" asp-controller="Result" asp-action="Index" method="get" class="form-inline" style="justify-content: center;">
    <div class="form-group mb-2">
        <label>Status:</label>
        <select name="Status" asp-items="sl" class="form-control ml-2">
            <option selected disabled>Wybierz status</option>
        </select>
    </div>
    <div class="form-group mb-2 ml-2">
        <label>Od: </label>
        <input name="FromDate" value=@ViewData["DateTime1"] class="form-control ml-2" type="datetime-local" />
        <label class="ml-2"> Do: </label>
        <input name="ToDate" value=@ViewData["DateTime2"] class="form-control ml-2" type="datetime-local" />
    </div>
    <div class="form-group mb-2 ml-2">
        <input type="submit" asp-controller="Event" asp-action="Map" class="btn btn-outline-primary" value="Filtruj" />
    </div>
    <div class="form-group mb-2 ml-2">
        <input type="submit" asp-controller="Event" asp-action="ClearForm" class="btn btn-outline-primary" value="Resetuj" />
    </div>
</form>
@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EventId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Point)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EventId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @status[item.Status]
            </td>
            <td>
                <a asp-controller="Point" asp-action="Details" asp-route-id="@item.PointId">@item.Point.Name</a>
            </td>
            <td>
                @Html.ActionLink("Edytuj", "Edit", new {  id=item.EventId  }) |
                @Html.ActionLink("Szczegóły", "Details", new { id = item.EventId }) |
                @Html.ActionLink("Usuń", "Delete", new { id = item.EventId })
            </td>
        </tr>
}
    </tbody>
</table>*@
<table class="table">
    <tr>
        <td colspan="3" rowspan="3" id="map">
        </td>
    </tr>
    <tr class="blankRow"></tr>
</table>
<script>

    var options = {
        center: [53.298244, 23.654148],
        zoom: 6
    }
    let marker, popup, lat, lng, latlng;
    var map = L.map('map', options);

    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    var arcgisOnline = L.esri.Geocoding.arcgisOnlineProvider();
    L.esri.Geocoding.geosearch({
        providers: [
            arcgisOnline,
            L.esri.Geocoding.mapServiceProvider({
                label: 'States and Counties',
                url: 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/Census/MapServer',
                layers: [2, 3],
                searchFields: ['NAME', 'STATE_NAME']
            })
        ],
        placeholder: "Szukaj..."
    }).addTo(map);
    @foreach (var item in Model) {
        if (item.Point.Latitude != null && item.Point.Longitude != null) {
        @:lat = parseFloat(@item.Point.Latitude);
        @:lng = parseFloat(@item.Point.Longitude);
        @:latlng = L.latLng(lat, lng);
        @:if (lat === undefined || lng === undefined) {
            @:console.log("brak danych");
        @:}
        @:else {
            @:marker = new L.marker(latlng).addTo(map);
            @:popup = L.popup().setContent('<strong>Klient: </strong><a href="/Client/Details/@item.Point.ClientId"><strong>@item.Point.Client.Name</strong></a><br>Punkt: <a href="/Point/Details/@item.PointId">@item.Point.Name</a><br>Zdarzenie: <a href="/Event/Details/@item.EventId">@item.Description</a><br>Opis punktu: @item.Point.Description<br>Do zrobienia: @item.Description<br>Data: @item.Date');
            @:marker.bindPopup(popup);
        @:}
        }
        
    }
</script>