praktyki/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using praktyki.Data;
using praktyki.Models;

namespace praktyki.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleController : Controller
    {
        RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<IdentityUser> _userManager;
        //private readonly Manager
        private readonly ApplicationDbContext _context;
        public RoleController(RoleManager<IdentityRole> roleManager, ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _roleManager = roleManager;
            _context = context;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            var roles = _roleManager.Roles.ToList();
            return View(roles);
        }
        public IActionResult ListUsers()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }
        public async Task<IActionResult> Update(string id)
        {
            IdentityRole role = await _roleManager.FindByIdAsync(id);
            List<IdentityUser> members = new List<IdentityUser>();
            List<IdentityUser> nonMembers = new List<IdentityUser>();
            foreach (IdentityUser user in _userManager.Users)
            {
                var list = await _userManager.IsInRoleAsync(user, role.Name) ? members : nonMembers;
                list.Add(user);
            }
            return View(new RoleEdit
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }
        [HttpPost]
        public async Task<IActionResult> Update(RoleModification model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (string userId in model.AddIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.AddToRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            RedirectToAction(nameof(Update));
                    }
                }
                foreach (string userId in model.DeleteIds ?? new string[] { })
                {
                    IdentityUser user = await _userManager.FindByIdAsync(userId);
                    if (user != null)
                    {
                        result = await _userManager.RemoveFromRoleAsync(user, model.RoleName);
                        if (!result.Succeeded)
                            RedirectToAction(nameof(Update));
                    }
                }
            }

            if (ModelState.IsValid)
                return RedirectToAction(nameof(Index));
            else
                return await Update(model.RoleId);
        }
        public async Task<IActionResult> EditUserRole(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var roles = await _userManager.GetRolesAsync(user);
            UserRoles ur = new UserRoles
            {
                UserId = user.Id,
                UserName = user.UserName,
                RoleNames = (List<string>)roles
            };
            ViewBag.RoleNames = new SelectList(_roleManager.Roles.ToList(), "Id", "Name");
            //ViewData["roles"] = roles;
            return View(ur);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteUserRole(string id, string role)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                await _userManager.RemoveFromRolesAsync(user, (IEnumerable<string>)role.ToList());
                return RedirectToAction(nameof(ListUsers));
            }
            catch (Exception e)
            {
                return View("Error");
            }
            
        }
        public async Task<IActionResult> DeleteUser(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            return View(user);
        }
        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var user = await _userManager.FindByIdAsync(id);
                await _userManager.DeleteAsync(user);
                return RedirectToAction(nameof(Index));
            }
            catch(Exception e)
            {
                return View("Error");
            }
            
        }
        public IActionResult Create()
        {
            return View(new IdentityRole());
        }
        //public async Task<IActionResult> DeleteFromUser()
        //{
        //    var userRoles = await _context.UserRoles.ToListAsync();
        //}
        [HttpPost]
        public async Task<IActionResult> Create (IdentityRole role)
        {
            await _roleManager.CreateAsync(role);
            return RedirectToAction("Index");
        }
        //public async Task<IActionResult> Delete()
        //{
        //    AspNetUserRoles anur = new AspNetUserRoles();
        //    anur = _context.UserRoles.Include(u => u.)
        //    return View(anur);
        //}
        // GET: Role/Assign
        public async Task<ActionResult> Manage()
        {
            var adminRole = await _roleManager.FindByNameAsync("Admin");
            var assignableRoles = _roleManager.Roles.ToList();
            //linijka nizej sprawia ze nie mozna przypisac nikogo do admina
            //assignableRoles.RemoveAt(assignableRoles.IndexOf(adminRole));
            ViewData["Name"] = new SelectList(assignableRoles, "Name", "Name");
            ViewData["UserName"] = new SelectList(_userManager.Users, "UserName", "UserName");
            return View(new RoleModel());
        }

        // POST: Role/Assign
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Manage(RoleModel roleModel)
        {
            if (ModelState.IsValid)
            {
                //Blokowanie przypisania komus admina
                //if (roleModel.Name == "Admin")
                //{
                //    ViewData["Message"] = "Invalid Request.";
                //    return View("Info");
                //}
                var user = await _userManager.FindByEmailAsync(roleModel.UserName);
                if (user != null)
                {
                    if (await _roleManager.RoleExistsAsync(roleModel.Name))
                    {
                        if (await _userManager.IsInRoleAsync(user, roleModel.Name))
                        {
                            ViewData["Message"] = $@"Użytkownik {roleModel.UserName} już posiada rolę {roleModel.Name}.";
                            return View("Info");
                        }
                        else
                        {
                            await _userManager.AddToRoleAsync(user, roleModel.Name);
                            ViewData["Message"] = $@"Użytkownik {roleModel.UserName} został przypisany do roli {roleModel.Name}.";
                            return View("Info");
                        }
                    }
                    else
                    {
                        ViewData["Message"] = "Invalid Request.";
                        return View("Info");
                    }
                }
                else
                {
                    ViewData["Message"] = "Invalid Request.";
                    return View("Info");
                }
            }
            return View(roleModel);
        }
    }
}

praktyki/Views/Role/Create.cshtml
@model Microsoft.AspNetCore.Identity.IdentityRole
@{
    ViewData["Title"] = "Dodaj rolę";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Dodaj rolę</h1>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="col-form-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div>
    <a asp-action="Index">Powrót do listy</a>
</div>
@section Scripts{ 
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

praktyki/Views/Role/DeleteUser.cshtml
@model Microsoft.AspNetCore.Identity.IdentityUser
@{
    ViewData["Title"] = "Usuń";
}

<h1>Usuń</h1>

<h3>Na pewno chcesz usunąć tego użytkownika?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UserName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserName)
        </dd>
    </dl>

    <form asp-action="DeleteUser">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Usuń" class="btn btn-danger" /> |
        <a asp-action="Index">Powrót do listy</a>
    </form>
</div>

praktyki/Views/Role/EditUserRole.cshtml
@model UserRoles
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h1>Usuń rolę</h1>
@{ 

}
<h3>Kliknij rolę, którą chcesz usunąć</h3>
<div>
    <hr />
    @Model.UserName
    @*@foreach (var item in Model)
    {
        <form asp-action="DeleteUserRole">
            <input type="hidden" asp-for="role"
            <input type="submit" class="btn btn-danger" value="@item.RoleNames"/>
        </form>

    }*@
    <hr />

    <select asp-for="@Model.RoleNames" asp-items="@ViewBag.RoleNames"></select>
    @*<form asp-action="Delete">
            <input type="hidden" asp-for="ClientId" />
            <input type="submit" value="Usuń" class="btn btn-danger" /> |
            <a asp-action="Index">Powrót do listy</a>
        </form>*@
</div>

praktyki/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityRole>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row">
    <div class="col">
        <h1>Lista ról</h1>
        <p>
            <a asp-action="Create">Utwórz rolę</a>
        </p>
    </div>
    <div class="col" style="display: flex; flex-direction: row; justify-content: flex-end; align-items: flex-end;">
        @*<div class="form-group">
            <form asp-controller="Service" asp-action="Index" method="get" style="display: inline-flex">
                <input type="submit" asp-controller="Role" asp-action="Manage" class="btn btn-outline-primary" value="Przypisz użytkownika do roli" />
            </form>
        </div>
        <div class="form-group ml-3">
            <form asp-controller="Service" asp-action="Index" method="get" style="display: inline-flex">
                <input type="submit" asp-controller="Role" asp-action="ListUsers" class="btn btn-outline-primary" value="Lista użytkowników" />
            </form>
        </div>
        <div class="form-group ml-3">
            <form method="get" style="display: inline-flex">
                <input type="submit" class="btn btn-outline-danger" value="Zabierz rolę użytkownikowi" />
            </form>
        </div>*@
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Nazwa</th>
            <th>Akcja</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var role in Model)
        {
            <tr>
                <td>@role.Id</td>
                <td>@role.Name</td>
                <td><a asp-action="Update" asp-route-id="@role.Id">Zarządzaj użytkownikami</a></td>
            </tr>
        }
    </tbody>
</table>

praktyki/Views/Role/Info.cshtml
@{
    ViewData["Title"] = "Info";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Info</h2>
<h3>@ViewData["Message"]</h3>

praktyki/Views/Role/ListUsers.cshtml
@model IEnumerable<Microsoft.AspNetCore.Identity.IdentityUser>

@{
    ViewBag.Title = "Lista użytkownków";
}

<h1>Lista użytkownków</h1>

@if (Model.Any())
{
    @*<a asp-action="Register" asp-controller="Account"
       class="btn btn-primary mb-3" style="width:auto">
        Add new user
    </a>*@

    foreach (var user in Model)
    {
        <div class="card mb-3">
            <div class="card-header">
                User Id : @user.Id
            </div>
            <div class="card-body">
                <h5 class="card-title">@user.UserName</h5>
            </div>
            <div class="card-footer">
                <a asp-controller="Role" asp-action="DeleteUser" asp-route-id="@user.Id" class="btn btn-danger">Usuń</a>
            </div>
        </div>
    }
}
else
{
    <div class="card">
        <div class="card-header">
            Brak użytkowników
        </div>
        <div class="card-body">
            <h5 class="card-title">
                Niech ktoś stworzy nowe konto
            </h5>
            @*<a class="btn btn-primary" style="width:auto"
               asp-controller="Account" asp-action="Register">
                Add new user
            </a>*@
        </div>
    </div>
}

praktyki/Views/Role/Manage.cshtml
@model RoleModel

@{
    ViewData["Title"] = "Assign";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Przypisz użytkownikowi rolę</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Manage">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <select asp-for="Name" class="form-control" asp-items="(SelectList)@ViewData["Name"]"></select>
            </div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <select asp-for="UserName" class="form-control" asp-items="(SelectList)@ViewData["UserName"]"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Przypisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Powrót do listy</a>
</div>

praktyki/Views/Role/Update.cshtml
@model RoleEdit

<h1>Edytuj rolę</h1>
<div asp-validation-summary="All" class="text-danger"></div>

<form method="post">
    <input type="hidden" name="roleName" value="@Model.Role.Name" />
    <input type="hidden" name="roleId" value="@Model.Role.Id" />

    <h2>Dodaj do roli @Model.Role.Name</h2>
    <table class="table table-bordered table-striped table-sm">
        @if (Model.NonMembers.Count() == 0)
        {
            <tr><td colspan="2">Wszyscy użytkownicy są w tej roli</td></tr>
        }
        else
        {
            @foreach (Microsoft.AspNetCore.Identity.IdentityUser user in Model.NonMembers)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="AddIds" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>

    <h2>Usuń z roli @Model.Role.Name</h2>
    <table class="table table-bordered table-striped table-sm">
        @if (Model.Members.Count() == 0)
        {
            <tr><td colspan="2">Nikt nie jest w tej roli</td></tr>
        }
        else
        {
            @foreach (Microsoft.AspNetCore.Identity.IdentityUser user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td>
                        <input type="checkbox" name="DeleteIds" value="@user.Id">
                    </td>
                </tr>
            }
        }
    </table>
    <button type="submit" class="btn btn-primary">Zapisz</button> |
    <a asp-action="Index">Powrót do listy</a>
</form>